name: Monitor Madonna Store Stock

on:
  push:
    branches:
      - main

  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Workflow avviato!"
