name: Schedule Test

run-name: "Schedule Test - ${{ github.event_name }} - run ${{ github.run_number }}"

on:
  schedule:
    - cron: '3,13,23,33,43,53 * * * *'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Diagnostica
        run: |
          echo "Evento: ${{ github.event_name }}"
          echo "Cron: ${{ github.event.schedule }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          date -u
